### ISSUE TITLE
[Helm 3] Plugin installation failed.

### ISSUE THREAD

**Issue by hack3d** [mbenabda/helm-local-chart-version#11]
The installation of the plugin with helm 3.0.1 failed. 
Terminal output:
`*   Trying 140.82.118.5...
* Connected to api.github.com (140.82.118.5) port 443 (#0)
* found 149 certificates in /etc/ssl/certs/ca-certificates.crt
* found 605 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: *.github.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=US,ST=California,L=San Francisco,O=GitHub\, Inc.,CN=*.github.com
* 	 start date: Mon, 08 Jul 2019 00:00:00 GMT
* 	 expire date: Thu, 16 Jul 2020 12:00:00 GMT
* 	 issuer: C=US,O=DigiCert Inc,OU=www.digicert.com,CN=DigiCert SHA2 High Assurance Server CA
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET /repos/mbenabda/helm-local-chart-version/releases/latest HTTP/1.1
> Host: api.github.com
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Mon, 10 Feb 2020 10:36:00 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 7836
< Server: GitHub.com
< Status: 200 OK
< X-RateLimit-Limit: 60
< X-RateLimit-Remaining: 57
< X-RateLimit-Reset: 1581334087
< Cache-Control: public, max-age=60, s-maxage=60
< Vary: Accept
< ETag: "86eeb89debc5c7d4f662563e00ce651d"
< Last-Modified: Sun, 10 Feb 2019 01:06:40 GMT
< X-GitHub-Media-Type: github.v3; format=json
< Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
< Access-Control-Allow-Origin: *
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Frame-Options: deny
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
< Content-Security-Policy: default-src 'none'
< Vary: Accept-Encoding, Accept
< Vary: Accept-Encoding
< X-GitHub-Request-Id: F0C4:2C0B6:6A028BA:7F50B00:5E413210
< 
{ [286 bytes data]
* Connection #0 to host api.github.com left intact
Downloading https://github.com/mbenabda/helm-local-chart-version/releases/download/v0.0.6/helm-local-chart-version-0.0.6-linux-amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   640    0   640    0     0   1357      0 --:--:-- --:--:-- --:--:--  1358
100 1375k  100 1375k    0     0   702k      0  0:00:01  0:00:01 --:--:-- 1020k
Preparing to install into The Kubernetes package manager

Common actions for Helm:

- helm search:    search for charts
- helm pull:      download a chart to your local directory to view
- helm install:   upload the chart to Kubernetes
- helm list:      list releases of charts

Environment variables:

+------------------+-----------------------------------------------------------------------------+
| Name             | Description                                                                 |
+------------------+-----------------------------------------------------------------------------+
| $XDG_CACHE_HOME  | set an alternative location for storing cached files.                       |
| $XDG_CONFIG_HOME | set an alternative location for storing Helm configuration.                 |
| $XDG_DATA_HOME   | set an alternative location for storing Helm data.                          |
| $HELM_DRIVER     | set the backend storage driver. Values are: configmap, secret, memory       |
| $HELM_NO_PLUGINS | disable plugins. Set HELM_NO_PLUGINS=1 to disable plugins.                  |
| $KUBECONFIG      | set an alternative Kubernetes configuration file (default "~/.kube/config") |
+------------------+-----------------------------------------------------------------------------+

Helm stores configuration based on the XDG base directory specification, so

- cached files are stored in $XDG_CACHE_HOME/helm
- configuration is stored in $XDG_CONFIG_HOME/helm
- data is stored in $XDG_DATA_HOME/helm

By default, the default directories depend on the Operating System. The defaults are listed below:

+------------------+---------------------------+--------------------------------+-------------------------+
| Operating System | Cache Path                | Configuration Path             | Data Path               |
+------------------+---------------------------+--------------------------------+-------------------------+
| Linux            | $HOME/.cache/helm         | $HOME/.config/helm             | $HOME/.local/share/helm |
| macOS            | $HOME/Library/Caches/helm | $HOME/Library/Preferences/helm | $HOME/Library/helm      |
| Windows          | %TEMP%\helm               | %APPDATA%\helm                 | %APPDATA%\helm          |
+------------------+---------------------------+--------------------------------+-------------------------+

Usage:
  helm [command]

Available Commands:
  completion          Generate autocompletions script for the specified shell (bash or zsh)
  create              create a new chart with the given name
  dependency          manage a chart's dependencies
  env                 Helm client environment information
  get                 download extended information of a named release
  help                Help about any command
  history             fetch release history
  install             install a chart
  kubeval             Validate Helm charts
  lint                examines a chart for possible issues
  list                list releases
  local-chart-version local-chart-version [subcommand] LOCAL_CHART_DIRECTORY [flags]
  package             package a chart directory into a chart archive
  plugin              install, list, or uninstall Helm plugins
  pull                download a chart from a repository and (optionally) unpack it in local directory
  repo                add, list, remove, update, and index chart repositories
  rollback            roll back a release to a previous revision
  search              search for a keyword in charts
  secrets             Secrets encryption in Helm for Git storing
  show                show information of a chart
  status              displays the status of the named release
  template            locally render templates
  test                run tests for a release
  uninstall           uninstall a release
  upgrade             upgrade a release
  verify              verify that a chart at the given path has been signed and is valid
  version             print the client version information

Flags:
      --add-dir-header                   If true, adds the file directory to the header
      --alsologtostderr                  log to standard error as well as files
      --debug                            enable verbose output
  -h, --help                             help for helm
      --kube-context string              name of the kubeconfig context to use
      --kubeconfig string                path to the kubeconfig file
      --log-backtrace-at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log-dir string                   If non-empty, write log files in this directory
      --log-file string                  If non-empty, use this log file
      --log-file-max-size uint           Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
      --logtostderr                      log to standard error instead of files (default true)
  -n, --namespace string                 namespace scope for this request (default "default")
      --registry-config string           path to the registry config file (default "/home/rlekies/.config/helm/registry.json")
      --repository-cache string          path to the file containing cached repository indexes (default "/home/rlekies/.cache/helm/repository")
      --repository-config string         path to the file containing repository names and URLs (default "/home/rlekies/.config/helm/repositories.yaml")
      --skip-headers                     If true, avoid header prefixes in the log messages
      --skip-log-headers                 If true, avoid headers when opening log files
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          number for the log level verbosity
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

Use "helm [command] --help" for more information about a command./plugins/helm-local-chart-version
mkdir: Unbekannte Option »--add-dir-header«
„mkdir --help“ liefert weitere Informationen.
Failed to install helm-local-chart-version
For support, go to https://github.com/mbenabda/helm-local-chart-version.
Error: plugin install hook for "local-chart-version" exited with error
`

**Comment by hack3d** [comment]
I found the error. You use $(helm home) which is removed in helm 3 (https://helm.sh/docs/topics/v2_v3_migration/). 
I added an PR #12.

**Comment by mbenabda** [comment]
thanks !
