### ISSUE TITLE
The plugin overwrites the existing Chart file

### ISSUE THREAD

**Issue by RoryOfByrne** [mbenabda/helm-local-chart-version#13]
It seems like the plugin overwrites the existing Chart.yml file to look like:
```
apiVersion: <version>
description: <description>
name: <name>
version: <semver>
```

It would be more useful for me if it updated my existing Chart file in-place.

**Comment by mbenabda** [comment]
hi there. could you elaborate on why this is a problem ?

This plugin uses the helm codebase (v2.8.1) as a library that abstracts yaml away to manipulate chart metadata and load/save the chart file.
That library doesn't provide a way to patch the file in place, so i'd need to not rely on it anymore to do that.
While that's not a big deal, i don't work with helm these days, and would need a valid reason to justify putting in the time to make that change.

**Comment by RoryOfByrne** [comment]
For example, I had `type: application` in my Chart file and after I ran the plugin it wasn't there anymore so I had to manually re-enter it. This defeats the purpose of the plugin: avoiding having to manually edit the chart file.

It's fine if you don't want to update it. I ended up writing a bash script to handle it so I won't be submitting a PR, maybe someone else will do it!

**Comment by mbenabda** [comment]
wow, sorry for the inconvenience, that is indeed an issue. The chartfile schema must've changed since i made the plugin, hence the missing keys
I'm on it and will release a fix ASAP.
thanks for reporting this
