### ISSUE TITLE
Version of the plugin to install is not correct 

### ISSUE THREAD

**Issue by IvanBasic-TomTom** [mbenabda/helm-local-chart-version#16]
If a folder where helm plugin install command is run is already a git repo it detects the tags of that repo as a version to install instad of tags for plugin repo

**Comment by mbenabda** [comment]
Hi there, sorry for the late answer (i'll admit it's waaaaay overdue !)

a simple workaround is not to run the install command from a git repo

feel free to submit a PRs if that's still an issue
