### ISSUE TITLE
Support for arm64

### ISSUE THREAD

**Issue by LesTR** [mbenabda/helm-local-chart-version#20]
After fixing https://github.com/mbenabda/helm-local-chart-version/issues/18 I'm unable to download `https://github.com/mbenabda/helm-local-chart-version/releases/download/v0.0.7/helm-local-chart-version-0.0.7-darwin-arm64.tar.gz` because it doesn't exist.

Any plan to add support for arm64?

**Comment by lzecca78** [comment]
I am interested too, afaik, it should be enough add `arm64` in the .goreleaser.yml in the array of goarch. 
If a PR is needed i am open to do that.

**Comment by mbenabda** [comment]
Hey guys,

> After fixing #18 I'm unable to download `https://github.com/mbenabda/helm-local-chart-version/releases/download/v0.0.7/helm-local-chart-version-0.0.7-darwin-arm64.tar.gz` because it doesn't exist.
> 
> Any plan to add support for arm64?

Not really, since i'm not using the project currently, i have no actual roadmap for it.
However, i am not at all against adding support if that fits anyone's needs

> I am interested too, afaik, it should be enough add `arm64` in the .goreleaser.yml in the array of goarch. If a PR is needed i am open to do that.

an it looks like it does ;)

I'd be happy to take a look at any PR you guys throw my way, feel free to go for it :)

**Comment by mbenabda** [comment]
@LesTR @lzecca78 
v0.1.0 is now available for arm64 !

```sh
# Linux
wget https://github.com/mbenabda/helm-local-chart-version/releases/download/v0.1.0/helm-local-chart-version-0.1.0-linux-arm64.tar.gz

# Mac OS
wget https://github.com/mbenabda/helm-local-chart-version/releases/download/v0.1.0/helm-local-chart-version-0.1.0-darwin-arm64.tar.gz
```
