### ISSUE TITLE
Make default chart . and default segment patch

### ISSUE THREAD

**Issue by yurrriq** [mbenabda/helm-local-chart-version#7]
At least for me, those are the most common values I'd want to use. If you're not amenable to it, I could easily make an alias. Thanks for this plugin!

**Comment by mbenabda** [comment]
hello.

the default chart creation feature is already available straight out of the box in helm. Try ```helm create mychart```
Could you elaborate a little more as of what you mean by "default segment patch" ?

**Comment by yurrriq** [comment]
I would like `helm local-chart-verison bump` to be equivalent to `helm local-chart-version bump -s patch .`.

**Comment by mbenabda** [comment]
thank you for the suggestion, but to be honest, this looks counter intuitive to me, and i'd rather have users explicitly choose the segment instead of having implicit behavior. plus I like the fact that the incomplete command brings up the usage help which lists all the valid segment values.

**Comment by yurrriq** [comment]
Ok, thanks for the response.
