### ISSUE TITLE
helm-local-chart-version fails to install

### ISSUE THREAD

**Issue by iksaif** [mbenabda/helm-local-chart-version#8]
Looks like you are being hit by the same issue as https://github.com/databus23/helm-diff/issues/10 (the same fix should work)

**Comment by mbenabda** [comment]
thank you! will look into it

**Comment by mbenabda** [comment]
it shouldn't call the github API anymore when installing a specific version. thank you for reporting the issue. could you confirm the new release fixes it for you ?
